version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'tutorial'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'tutorial'
        #volumes:
        #    - mysqldata:/var/lib/mysql
        ports:
            - 3308:3306
    db_seeder:
        image: mysql:latest
        volumes:
            - ./table.sql:/table.sql    
        entrypoint: [ "bash", "-c", "sleep 20 && mysql --user=root --password=secret --host=mysql --port=3306 tutorial < /table.sql && exit"] 
        depends_on:
            - mysql
    cron:
        build:
            context: .
            dockerfile: CRON.Dockerfile
        entrypoint: [ "bash", "-c", "cron -f"] 
        depends_on:
            - db_seeder
    minima:
        image: minimaglobal/minima:dev
        stop_grace_period: 60s
        environment:
            minima_solo: true
            minima_rpcenable: true
            minima_mdsenable: true
            minima_mdspassword: "123"
        ports:
            - 9999:9003
        volumes:
            - ./minima:/home/minima/data
    #OPTIONAL - our nice UI to browse our mysql db
    phpmyadmin:
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            # we specify that we connect to an arbitrary server with the flag below
            # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
            - PMA_ARBITRARY=1
        depends_on:
            - db_seeder
#volumes:
#    mysqldata: {}